### ISSUE TITLE
Failed to load the quick-jump package

### ISSUE THREAD

**Issue by sean-sh** [kelp404/quick-jump#14]
Happened right after install.

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [quick-jump](https://github.com/kelp404/quick-jump) package, v0.0.4
### Stack Trace

Failed to load the quick-jump package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/sean/.atom/packages/quick-jump/lib/quick-jump-view.coffee:4:199)
  at /Users/sean/.atom/packages/quick-jump/lib/quick-jump-view.coffee:6:5
  at Object.<anonymous> (/Users/sean/.atom/packages/quick-jump/lib/quick-jump-view.coffee:275:5)
  at Object.<anonymous> (/Users/sean/.atom/packages/quick-jump/lib/quick-jump-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/sean/.atom/packages/quick-jump/lib/quick-jump.coffee:1:17)
  at Object.<anonymous> (/Users/sean/.atom/packages/quick-jump/lib/quick-jump.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:707:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:451:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -2:51.8.0 jumpy:toggle (atom-text-editor.editor.is-focused)
     -2:50.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:46.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:46.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:43.4.0 jumpy:toggle (atom-text-editor.editor.is-focused)
     -2:36.1.0 core:cancel (a.stack-toggle)
     -2:35.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:34.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:34.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:33.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 61x -2:30.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
 10x -2:25 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -2:23 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:20.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:20.9.0 jumpy:toggle (atom-text-editor.editor)
     -0:19.3.0 core:cancel (a.btn-issue.btn.btn-error)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.6
emacs, v0.7.2
linter, v0.12.6
omnisharp-atom, v0.12.0
quick-jump, v0.0.4

# Dev
No dev packages
```

**Comment by GeertJohan** [comment]
@kelp404 can we expect a fix? I like the quick-jump package but it's not usable right now. If you don't have time to create a fix I would like to take over maintenance.

**Comment by j-walker23** [comment]
That would be awesome!

**Comment by benfrain** [comment]
Yes, same here. Cannot read property 'prototype' of undefined

**Comment by dustinchang** [comment]
@kelp404  I'd also like to know if this will be fixed, as this is the best implementation for Atom of the "easymotion" package I have found compared to Sublimes "easymotion" package. I'd be willing to learn and contribute with @GeertJohan as well.

**Comment by benfrain** [comment]
You may also want to look at 'Jumpy'

**Comment by guerrero** [comment]
IMHO the most similar plugin you can use is [easy-motion-redux](https://github.com/leny/atom-easy-motion-redux).
